name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Triggers on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter 3.27
        uses: subosito/flutter-action@v2
        with:
          # Use the flutter-version input to specify the exact version
          flutter-version: '3.27.0' # Use '3.27.0' or the specific patch version
          channel: 'stable'        # Still specify the channel for context

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web App
        run: flutter build web --release

      # Deploy the app to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: easy-orders-18
          channelId: live
          entryPoint: ./
